# This is a basic workflow to help you get started with Actions
<!DOCTYPE html>
<html>
  <head>
    <title>Terceiro projeto de RA usando o marcador Hiro e mostrando um modelo 3D</title>
    <script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/AR-js-org/AR.js/aframe/build/aframe-ar.min.js"></script>
  </head>
  <body style="margin: 0; overflow: hidden;">
      <a-scene vr-mode-ui="enabled: false" embedded arjs="debugUIEnabled: false">
        <a-assets>
          <a-asset-item id="cubo-esfera" src="modelo.glb"></a-asset-item>
        </a-assets>
      <a-marker preset="hiro">
      <a-entity id="cubo-esfera-na-cena"
        gltf-model="#cubo-esfera">
        </a-entity>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
    
  </body>
</html>
